Repository Minjae-An/Cockpybara, pull requests merged in 2023-07, with the labels that each got.

#21 Feature/#5
  Cockpybara/build.gradle
  Cockpybara/src/main/java/Alchole_free/Cockpybara/constant/RegexConstant.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/MemberController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/constant/RegexConstant.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/detail/DetailRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/detail/DetailResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/join/JoinRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/join/JoinResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/util/HashingUtil.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/Gender.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/Member.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/MemberRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/MemberService.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/repository/MemberRepositoryTest.java
  README.md
Labels: enhancement, :boom: BE

#24 Feature/#23
  Cockpybara/build.gradle
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/login/LoginController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/login/find_email/FindEmailRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/login/find_email/FindEmailResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/login/find_password/FindPasswordRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/login/set_new_password/SetNewPasswordRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/MemberController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/AlcoholicType.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/Category.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/CocktailRecipe.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/Glass.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/CocktailRecipeRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/MemberRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/MemberService.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/all_drinks.csv
Labels: enhancement, :boom: BE

#27 Feature/#25
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/MemberController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/MemberService.java
Labels: enhancement, :boom: BE

#31 Feature/#28
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/MemberController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/update/MemberInfoUpdateRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/update/MemberInfoUpdateResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/Member.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/MemberService.java
Labels: enhancement, :boom: BE

#35 Refactor/#23
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/login/LoginController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/Member.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/MemberService.java
Labels: :boom: BE, refactor

#44 Feature/#39
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/community/CommunityController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/community/member_info/MemberInfoResponse.java
Labels: enhancement, :boom: BE

#47 Feature/#30
  Cockpybara/src/main/java/Alchole_free/Cockpybara/CockpybaraApplication.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/ingredient/CSVToIngredientObjectMapping.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/ingredient/Ingredient.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/ingredient/IngredientCategory.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/ingredient/RecipeIngredient.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/ingredient/Unit.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/IngredientRepository.java
  Cockpybara/src/main/resources/all_drinks.csv
  Cockpybara/src/main/resources/all_ingredients.csv
  Cockpybara/src/main/resources/ingredients_classification.csv
  Cockpybara/src/main/resources/ingredients_list.csv
  Cockpybara/src/main/resources/refined_drinks.csv
  Cockpybara/src/test/java/Alchole_free/Cockpybara/all_drinks.csv
Labels: enhancement, :boom: BE

#45 Feature/#10 2
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/CocktailRecipeController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/option_list/CocktailRecipeSearchOptionListResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/search_by_name/FindCocktailRecipeByNameResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/login/LoginController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/MemberController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/CocktailRecipeRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/cocktail_recipe/CocktailRecipeService.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/MemberService.java
Labels: enhancement, :boom: BE

#51 Feature/#36
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/CocktailRecipe.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/taste/RecipeTaste.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/taste/Taste.java
Labels: enhancement, :boom: BE

#52 feat : CocktailRecipe createdAt 필드 추가(#37)
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/CocktailRecipe.java
Labels: enhancement, :boom: BE

#53 Feature/#41
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/CocktailRecipe.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/review/Review.java
Labels: enhancement, :boom: BE

#54 Feature/#46
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/community/CommunityController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/MemberController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/detail/DetailResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/update/MemberInfoUpdateResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/member/Gender.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/member/Member.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/member/likes/Like.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/MemberRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/MemberService.java
Labels: enhancement, :boom: BE

#67 Feature/#7
  Cockpybara/src/main/java/Alchole_free/Cockpybara/CockpybaraApplication.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/CocktailRecipeController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/recipe_detail/CocktailRecipeDetailResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/community/CommunityController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/cocktail_recipe/CocktailRecipeService.java
Labels: enhancement, :boom: BE

#70 Feature/#61
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/MyRecipeController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/update_my_recipe/UpdateMyRecipeRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/CocktailRecipe.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/cocktail_recipe/CocktailRecipeService.java
Labels: enhancement, :boom: BE

#72 Feature/#71
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/likes/LikesController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/member/likes/Like.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/MemberService.java
Labels: enhancement, :boom: BE

#74 Feature/#73
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/review/ReviewController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/review/add_review/AddReviewRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/review/Review.java
Labels: enhancement, :boom: BE

#81 Feature/#79
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/ingredient/IngredientController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/ingredient/search_ingredient/SearchIngredientResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/IngredientRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/ingredient/IngredientService.java
Labels: enhancement, :boom: BE

#75 refactor: 메인 css 수정
  Cockpybara/src/main/frontend/src/Home.js
  Cockpybara/src/main/frontend/src/MainMain.css
  Cockpybara/src/main/frontend/src/MainMain.js
  Cockpybara/src/main/frontend/src/photo/Cock2.png
  Cockpybara/src/main/frontend/src/photo/Cock3.png
Labels: :running_woman: FE

#84 feat: 커뮤니티 코드 수정
  Cockpybara/src/main/frontend/src/CocktailListSection.js
  Cockpybara/src/main/frontend/src/Community.js
  Cockpybara/src/main/frontend/src/MonthlyPopularSection.js
  Cockpybara/src/main/frontend/src/MyCommunitySection.js
  Cockpybara/src/main/frontend/src/components/Menu.css
Labels: :running_woman: FE, refactor
