Repository Minjae-An/Cockpybara, pull requests merged in 2023-08, with the labels that each got.

#85 Feature/#82
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/ingredient/IngredientUnitMap.java
  Cockpybara/src/main/resources/ingredients_classification.csv
  Cockpybara/src/main/resources/refined_drinks.csv
Labels: enhancement, :boom: BE

#87 레시피 추가 헤더
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/DetailHeader.js
  Cockpybara/src/main/frontend/src/NewMenu.css
  Cockpybara/src/main/frontend/src/NewMenu.js
  Cockpybara/src/main/frontend/src/components/Menu.js
Labels: :running_woman: FE, refactor

#88 Feature/#38
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/community/CommunityController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/CocktailRecipe.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/timePeriod/TimePeriod.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/ingredient/IngredientUnitMap.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/CocktailRecipeRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/cocktail_recipe/CocktailRecipeService.java
Labels: enhancement, :boom: BE

#89 refactor : ReviewController deleteReview 수정(#76)
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/review/ReviewController.java
Labels: :boom: BE, refactor

#93 feat: 서브 메뉴바 수정
  Cockpybara/src/main/frontend/src/DetailHeader.js
  Cockpybara/src/main/frontend/src/MainMain.css
  Cockpybara/src/main/frontend/src/NewMenu.css
  Cockpybara/src/main/frontend/src/NewMenu.js
  Cockpybara/src/main/frontend/src/NewNavBar.css
  Cockpybara/src/main/frontend/src/NewNavBar.js
Labels: :running_woman: FE, refactor

#94 refactor: 디테일 헤더 서치 컴포넌트 분리 및 css 재적용
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/DetailHeader.css
  Cockpybara/src/main/frontend/src/DetailHeader.js
  Cockpybara/src/main/frontend/src/HeaderSearch.css
  Cockpybara/src/main/frontend/src/HeaderSearch.js
  Cockpybara/src/main/frontend/src/MainHeader.css
  Cockpybara/src/main/frontend/src/MainHeader.js
  Cockpybara/src/main/frontend/src/NewMenu.js
  Cockpybara/src/main/frontend/src/NewNavBar.css
  Cockpybara/src/main/frontend/src/photo/MenuBarBlack.png
Labels: :running_woman: FE, refactor

#92 refactor getCocktailRecipesByPeriod(#38)
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/CocktailRecipeController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/community/CommunityController.java
Labels: :boom: BE, refactor

#99 Feature/#97
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/CocktailRecipeController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/timePeriod/TimePeriod.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/timeperiod/TimePeriod.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/CocktailRecipeRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/cocktail_recipe/CocktailRecipeService.java
Labels: :boom: BE, refactor, fix

#96 Feature/#10 3
  Cockpybara/.gradle/7.6.1/executionHistory/executionHistory.bin
  Cockpybara/.gradle/7.6.1/executionHistory/executionHistory.lock
  Cockpybara/.gradle/7.6.1/fileHashes/fileHashes.bin
  Cockpybara/.gradle/7.6.1/fileHashes/fileHashes.lock
  Cockpybara/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  Cockpybara/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Cockpybara/.gradle/buildOutputCleanup/outputFiles.bin
  Cockpybara/build.gradle
  Cockpybara/build/generated/querydsl/Alchole_free/Cockpybara/domain/cocktail_recipe/QCocktailRecipe.java
  Cockpybara/build/generated/querydsl/Alchole_free/Cockpybara/domain/cocktail_recipe/review/QReview.java
  Cockpybara/build/generated/querydsl/Alchole_free/Cockpybara/domain/cocktail_recipe/taste/QRecipeTaste.java
  Cockpybara/build/generated/querydsl/Alchole_free/Cockpybara/domain/ingredient/QIngredient.java
  Cockpybara/build/generated/querydsl/Alchole_free/Cockpybara/domain/ingredient/QRecipeIngredient.java
  Cockpybara/build/generated/querydsl/Alchole_free/Cockpybara/domain/member/QMember.java
  Cockpybara/build/generated/querydsl/Alchole_free/Cockpybara/domain/member/likes/QLike.java
  Cockpybara/build/generated/querydsl/Alchole_free/Cockpybara/domain/member/my_recipe/QMyRecipe.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/config/QueryDslConfig.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/CocktailRecipeController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/time_period/TimePeriod.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/cocktail_recipe/CocktailRecipeRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/cocktail_recipe/CocktailRecipeRepositoryImpl.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/cocktail_recipe/CocktailRepositoryCustom.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/cocktail_recipe/condition/CocktailRecipeSearchCondition.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/cocktail_recipe/CocktailRecipeService.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/review/ReviewService.java
Labels: enhancement, :boom: BE

#101 fix : MyRecipeController getRecipeOptionValues URL 변경(#100)
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/MyRecipeController.java
Labels: :boom: BE, fix

#104 Refactor/#103
  Cockpybara/.gradle/7.6.1/checksums/md5-checksums.bin
  Cockpybara/.gradle/7.6.1/checksums/sha1-checksums.bin
  Cockpybara/.gradle/file-system.probe
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/MemberController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/constant/RegexConstant.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/detail/DetailResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/join/JoinRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/update/MemberInfoUpdateResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/member/Gender.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/member/Member.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/MemberService.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/member_detail/MemberDetailDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/member_update/MemberUpdateDTO.java
  Cockpybara/src/main/resources/application.properties
  Cockpybara/src/test/java/Alchole_free/Cockpybara/CsvToCocktailRecipeMapping.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/domain/AlcoholicType.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/domain/Category.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/domain/CocktailRecipeForCsv.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/domain/Glass.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/domain/member/MemberSaveTest.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/domain/member/generate/MemberDummyGenerator.java
  Cockpybara/src/test/resource/member_mock_data.json
Labels: :boom: BE, refactor

#107 Refactor/#106
  Cockpybara/.gradle/7.6.1/executionHistory/executionHistory.bin
  Cockpybara/.gradle/7.6.1/executionHistory/executionHistory.lock
  Cockpybara/.gradle/7.6.1/fileHashes/fileHashes.bin
  Cockpybara/.gradle/7.6.1/fileHashes/fileHashes.lock
  Cockpybara/.gradle/7.6.1/fileHashes/resourceHashesCache.bin
  Cockpybara/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Cockpybara/.gradle/file-system.probe
  Cockpybara/build/generated/querydsl/Alchole_free/Cockpybara/domain/member/QMember.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/constant/RegexConstant.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/CsvToCocktailRecipeMapping.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/repository/CocktailRecipeRepositoryTest.java
  Cockpybara/src/test/java/Alchole_free/Cockpybara/repository/MemberRepositoryTest.java
  Cockpybara/src/test/resource/member_mock_data.json
Labels: :boom: BE, refactor

#112 refactor : CommunityController 리팩토링(#111)
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/community/CommunityController.java
Labels: :boom: BE, refactor

#118 Feature/#117
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/CocktailListSection.css
  Cockpybara/src/main/frontend/src/CocktailListSection.js
  Cockpybara/src/main/frontend/src/Community.css
  Cockpybara/src/main/frontend/src/MonthlyPopularSection.css
  Cockpybara/src/main/frontend/src/MonthlyPopularSection.js
  Cockpybara/src/main/frontend/src/MyCommunitySection.css
  Cockpybara/src/main/frontend/src/footer.css
  Cockpybara/src/main/frontend/src/footer.js
  Cockpybara/src/main/frontend/src/footerV2.css
  Cockpybara/src/main/frontend/src/footerV2.js
  Cockpybara/src/main/frontend/src/photo/chat.png
  Cockpybara/src/main/frontend/src/photo/good.png
  Cockpybara/src/main/frontend/src/photo/image1.png
  Cockpybara/src/main/frontend/src/photo/pinkTea.png
Labels: :running_woman: FE

#116 Refactor/#115
  Cockpybara/src/main/resources/refined_drinks.csv
Labels: :boom: BE, documentation, fix

#125 Refactor/#121
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/CocktailRecipeController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/option_list/CocktailRecipeSearchOptionListResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/recipe_detail/CocktailRecipeDetailDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/recipe_detail/ingredient/IngredientDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/recipe_detail/review/ReviewDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/search/CocktailRecipeSearchDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/CocktailRecipe.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/taste/RecipeTaste.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/ingredient/RecipeIngredient.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/cocktail_recipe/CocktailRecipeRepositoryImpl.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/cocktail_recipe/CocktailRecipeService.java
  Cockpybara/src/main/resources/refined_drinks.csv
  Cockpybara/src/test/java/Alchole_free/Cockpybara/domain/cocktail_recipe/recipe_taste/RecipeTasteSaveTest.java
Labels: :boom: BE, refactor

#129 Refactor/#128
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/timeperiod/TimePeriod.java
Labels: :boom: BE, refactor

#132 Refactor/#123
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/MyRecipeController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/add_new_my_recipe/AddNewMyRecipeRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/add_new_my_recipe/AddNewMyRecipeResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/add_new_my_recipe/MyRecipeIngredientDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/my_recipes/MyRecipeDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/recipe_options/RecipeOptionsResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/update_my_recipe/UpdateMyRecipeRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/update_my_recipe/UpdateMyRecipeResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/CocktailRecipe.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/member/Member.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/cocktail_recipe/CocktailRecipeService.java
Labels: :boom: BE, refactor

#139 Feature/#138
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/Join.js
Labels: :running_woman: FE

#142 Frontend
  Cockpybara/src/main/frontend/package.json
  Cockpybara/src/main/frontend/src/Join.css
  Cockpybara/src/main/frontend/src/Join.js
  Cockpybara/src/main/frontend/src/MonthlyPopularSection.js
Labels: :running_woman: FE, refactor

#143 Feature/#138
  Cockpybara/src/main/frontend/src/Join.js
Labels: :running_woman: FE

#144 Frontend
  Cockpybara/src/main/frontend/src/Join.js
Labels: :running_woman: FE

#145 Frontend
  Cockpybara/src/main/frontend/src/Join.js
Labels: :running_woman: FE, refactor

#146 Frontend
  Cockpybara/src/main/frontend/src/Join.js
Labels: :running_woman: FE, refactor

#150 Feature/#131
  Cockpybara/build.gradle
  Cockpybara/build/generated/querydsl/Alchole_free/Cockpybara/domain/member/QMember.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/config/GoogleDriveConfig.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/MemberController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/join/JoinRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/member/Member.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/image/ImageController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/image/ImageService.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/MemberService.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/member_detail/MemberDetailDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/member_update/MemberUpdateDTO.java
  Cockpybara/src/main/resources/application.properties
  Cockpybara/src/main/resources/client_secrets.json
  Cockpybara/src/test/java/Alchole_free/Cockpybara/domain/member/MemberSaveTest.java
Labels: enhancement, :boom: BE

#152 Feature/#151
  Cockpybara/src/main/frontend/package.json
  Cockpybara/src/main/frontend/src/About.css
  Cockpybara/src/main/frontend/src/About.js
  Cockpybara/src/main/frontend/src/IDFinder.js
  Cockpybara/src/main/frontend/src/Join.js
  Cockpybara/src/main/frontend/src/photo/arrow-bottom.png
  Cockpybara/src/main/frontend/src/photo/cock-circle.png
  Cockpybara/src/main/frontend/src/photo/copybara_orange.png
Labels: :running_woman: FE

#154 비밀번호 찾기 API 일단 추가
  Cockpybara/src/main/frontend/src/PWFinder.js
Labels: :running_woman: FE, refactor

#157 메인 이미지 추가
  Cockpybara/src/main/frontend/src/About.js
  Cockpybara/src/main/frontend/src/IDFinder.js
  Cockpybara/src/main/frontend/src/Login.js
  Cockpybara/src/main/frontend/src/MainMain.js
  Cockpybara/src/main/frontend/src/photo/Cock4.png
  Cockpybara/src/main/frontend/src/photo/Cock5.png
Labels: :running_woman: FE, refactor
