Repository Minjae-An/Cockpybara, pull requests merged in 2023-09, with the labels that each got.

#159 Refactor/#134
  Cockpybara/src/main/java/Alchole_free/Cockpybara/config/WebConfig.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/constant/SessionLoginConst.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/CocktailRecipeController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/recipe_detail/CocktailRecipeDetailDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/search/CocktailRecipeSearchDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/search_by_name/FindCocktailRecipeByNameResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/likes/LikesController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/login/LoginController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/login/LoginRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/my_recipe/MyRecipeController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/pagination/CustomPageRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/pagination/CustomPageResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/review/ReviewController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/exception/DefaultExceptionHandler.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/exception/ErrorResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/exception/member/DuplicateMemberException.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/interceptor/LoginInterceptor.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/ReviewRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/cocktail_recipe/CocktailRecipeRepository.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/cocktail_recipe/CocktailRecipeRepositoryCustom.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/repository/cocktail_recipe/CocktailRecipeRepositoryImpl.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/cocktail_recipe/CocktailRecipeService.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/MemberService.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/review/ReviewService.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/util/pagination/CustomPageRequest.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/util/pagination/CustomPageResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/util/pagination/PagingUtil.java
Labels: :boom: BE, refactor

#160 Feature/#158
  Cockpybara/src/main/frontend/src/AddRecipe.css
  Cockpybara/src/main/frontend/src/AddRecipe.js
  Cockpybara/src/main/frontend/src/AddRecipe2.css
  Cockpybara/src/main/frontend/src/AddRecipe2.js
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/MainMain.css
  Cockpybara/src/main/frontend/src/MainMain.js
  Cockpybara/src/main/frontend/src/photo/camera.png
Labels: :running_woman: FE, refactor

#161 Feature/#158
  Cockpybara/src/main/frontend/src/AddRecipe2.css
  Cockpybara/src/main/frontend/src/AddRecipe2.js
Labels: :running_woman: FE, refactor

#162 통신코드 각주 처리
  Cockpybara/src/main/frontend/src/AddRecipe2.js
Labels: :running_woman: FE

#164 refactor: 레시피 추가 백엔드 코드 추가
  Cockpybara/src/main/frontend/src/AddRecipe2.css
  Cockpybara/src/main/frontend/src/AddRecipe2.js
  Cockpybara/src/main/frontend/src/photo/ingredient-plus.png
Labels: :running_woman: FE, refactor

#165 Feature/#156
  Cockpybara/build.gradle
  Cockpybara/build/resources/main/application.properties
  Cockpybara/src/main/java/Alchole_free/Cockpybara/config/Aws3Config.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/config/GoogleDriveConfig.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/community/CommunityController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/community/member_info/MemberInfoResponse.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/member/MemberController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/image/ImageController.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/image/ImageService.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/MemberService.java
  Cockpybara/src/main/resources/application.properties
  Cockpybara/src/main/resources/client_secrets.json
Labels: enhancement, :boom: BE

#166 Feature/#148
  Cockpybara/src/main/frontend/package.json
  Cockpybara/src/main/frontend/src/About.css
  Cockpybara/src/main/frontend/src/About.js
  Cockpybara/src/main/frontend/src/App.css
  Cockpybara/src/main/frontend/src/Join.js
  Cockpybara/src/main/frontend/src/photo/Union.png
  Cockpybara/src/main/frontend/src/photo/Union2.png
  Cockpybara/src/main/frontend/src/photo/arrow-bottom.png
  Cockpybara/src/main/frontend/src/photo/cock-circle.png
  Cockpybara/src/main/frontend/src/photo/copybara_orange.png
  Cockpybara/src/main/frontend/src/photo/js.png
  Cockpybara/src/main/frontend/src/photo/mj.png
  Cockpybara/src/main/frontend/src/photo/sh.png
  Cockpybara/src/main/frontend/src/photo/sj.png
Labels: :running_woman: FE

#167 Feature/#158
  Cockpybara/src/main/frontend/src/AddRecipe.css
  Cockpybara/src/main/frontend/src/AddRecipe.js
  Cockpybara/src/main/frontend/src/AddRecipe2.css
  Cockpybara/src/main/frontend/src/AddRecipe2.js
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/IDFinder.js
  Cockpybara/src/main/frontend/src/Login.js
  Cockpybara/src/main/frontend/src/MainMain.css
  Cockpybara/src/main/frontend/src/MainMain.js
  Cockpybara/src/main/frontend/src/PWFinder.js
  Cockpybara/src/main/frontend/src/photo/Cock4.png
  Cockpybara/src/main/frontend/src/photo/Cock5.png
  Cockpybara/src/main/frontend/src/photo/camera.png
  Cockpybara/src/main/frontend/src/photo/ingredient-plus.png
Labels: :running_woman: FE, refactor

#171 Frontend
  Cockpybara/bin/main/Alchole_free/Cockpybara/CockpybaraApplication.class
  Cockpybara/bin/main/application.properties
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/MonthlyPopularSection.js
  Cockpybara/src/main/frontend/src/MyCommunitySection.js
  Cockpybara/src/main/frontend/src/Recipe.css
  Cockpybara/src/main/frontend/src/Recipe.js
  Cockpybara/src/main/frontend/src/RecipeDetail.css
  Cockpybara/src/main/frontend/src/RecipeDetail.js
Labels: :running_woman: FE, refactor

#176 커뮤니티 사용자 이름 불러오기 API
  Cockpybara/src/main/frontend/src/Community.css
  Cockpybara/src/main/frontend/src/MyCommunitySection.js
Labels: :running_woman: FE, refactor

#178 사용자 사진 get API 추가
  Cockpybara/src/main/frontend/src/MyCommunitySection.js
Labels: :running_woman: FE, refactor

#179 커뮤니티 칵테일 정보에서 useID 띄워주기 API 작성
  Cockpybara/src/main/frontend/src/CocktailListSection.js
Labels: :running_woman: FE, refactor

#180 커뮤니티 최신순 정렬 API 추가
  Cockpybara/src/main/frontend/src/CocktailListSection.js
Labels: :running_woman: FE, refactor

#181 커뮤니티 가나다순 API 추가
  Cockpybara/src/main/frontend/src/CocktailListSection.js
  Cockpybara/src/main/frontend/src/Community.css
  Cockpybara/src/main/frontend/src/Community.js
  Cockpybara/src/main/frontend/src/DetailHeader.css
  Cockpybara/src/main/frontend/src/HeaderSearch.css
  Cockpybara/src/main/frontend/src/MyCommunitySection.js
  Cockpybara/src/main/frontend/src/NewMenu.css
  Cockpybara/src/main/frontend/src/Recipe.js
  Cockpybara/src/main/frontend/src/photo/Vector (9).png
Labels: :running_woman: FE, refactor

#182 css 수정
  Cockpybara/src/main/frontend/src/Community.js
  Cockpybara/src/main/frontend/src/DetailHeader.css
Labels: :running_woman: FE, refactor

#175 Frontend
  Cockpybara/src/main/frontend/src/CocktailListSection.js
  Cockpybara/src/main/frontend/src/Community.css
  Cockpybara/src/main/frontend/src/Community.js
  Cockpybara/src/main/frontend/src/HeaderSearch.css
  Cockpybara/src/main/frontend/src/MyCommunitySection.js
  Cockpybara/src/main/frontend/src/NewMenu.css
  Cockpybara/src/main/frontend/src/Recipe.js
  Cockpybara/src/main/frontend/src/photo/Vector (9).png
Labels: :running_woman: FE, refactor

#186 Feature/#185
  Cockpybara/src/main/frontend/src/Recipe.js
  Cockpybara/src/main/frontend/src/RecipeDetail.js
Labels: :running_woman: FE, refactor

#188 칵테일 정보 - 이름 불러오기 API 추가
  Cockpybara/src/main/frontend/src/RecipeDetail.js
Labels: :running_woman: FE, refactor

#189 칵테일 설명 API 추가
  Cockpybara/src/main/frontend/src/RecipeDetail.js
Labels: :running_woman: FE, refactor

#191 재료 API 추가
  Cockpybara/src/main/frontend/src/RecipeDetail.js
Labels: :running_woman: FE, refactor

#192 Feature/#190
  Cockpybara/src/main/resources/assests/cocktail_search_image.JPG
  Cockpybara/src/main/resources/assests/community_image.JPG
  Cockpybara/src/main/resources/assests/main.JPG
  Cockpybara/src/main/resources/assests/main_image.JPG
  Cockpybara/src/main/resources/assests/pjAn.jpg
  Cockpybara/src/main/resources/assests/pjJun.jpg
  Cockpybara/src/main/resources/assests/pjKim.jpg
  Cockpybara/src/main/resources/assests/pjSin.jpg
  Cockpybara/src/main/resources/assests/recipe_detail_image.JPG
  README.md
Labels: documentation

#187 레시피 디테일 사진 불러오기 API 작성
  Cockpybara/src/main/frontend/src/Recipe.js
  Cockpybara/src/main/frontend/src/RecipeDetail.js
Labels: :running_woman: FE, refactor

#193 README문법 수정
  README.md
Labels: documentation, fix

#195 Feat/#194
  Cockpybara/src/main/java/Alchole_free/Cockpybara/controller/cocktailrecipe/search/CocktailRecipeSearchDTO.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/domain/cocktail_recipe/CocktailRecipe.java
  Cockpybara/src/main/java/Alchole_free/Cockpybara/service/member/MemberService.java
Labels: enhancement, :boom: BE

#198 Feature/#197
  Cockpybara/src/main/frontend/src/CocktailListSection.js
  Cockpybara/src/main/frontend/src/Comment.css
  Cockpybara/src/main/frontend/src/Comment.js
  Cockpybara/src/main/frontend/src/CommentForm.js
  Cockpybara/src/main/frontend/src/Community.js
  Cockpybara/src/main/frontend/src/DetailHeader.css
  Cockpybara/src/main/frontend/src/MonthlyPopularSection.js
  Cockpybara/src/main/frontend/src/MyCommunitySection.js
  Cockpybara/src/main/frontend/src/Recipe.js
  Cockpybara/src/main/frontend/src/RecipeDetail.js
Labels: :running_woman: FE, refactor

#200 칵테일 디테일 1차 완료
  Cockpybara/src/main/frontend/src/RecipeDetail.css
  Cockpybara/src/main/frontend/src/RecipeDetail.js
  Cockpybara/src/main/frontend/src/photo/sob.png
Labels: :running_woman: FE, refactor

#201 커뮤니티 더미데이터 수정
  Cockpybara/src/main/frontend/src/MonthlyPopularSection.js
Labels: :running_woman: FE, refactor

#204 로그인 축하페이지
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/Join.js
  Cockpybara/src/main/frontend/src/JoinComplete.css
  Cockpybara/src/main/frontend/src/JoinComplete.js
  Cockpybara/src/main/frontend/src/photo/JoinComplete.png
Labels: :running_woman: FE, refactor, fix

#205 Feature/#203
  Cockpybara/src/main/frontend/src/About.js
  Cockpybara/src/main/frontend/src/Recipe.js
Labels: :running_woman: FE, refactor

#206 Refactor/community cocktail list
  Cockpybara/src/main/frontend/src/CocktailListSection.css
  Cockpybara/src/main/frontend/src/CocktailListSection.js
Labels: :running_woman: FE, refactor

#208 디테일 코멘트 추가
  Cockpybara/src/main/frontend/src/RecipeDetail.css
  Cockpybara/src/main/frontend/src/RecipeDetail.js
  Cockpybara/src/main/frontend/src/photo/star.png
Labels: :running_woman: FE, refactor

#210 Feature/#207
  Cockpybara/src/main/frontend/src/About.js
  Cockpybara/src/main/frontend/src/AddRecipe.css
  Cockpybara/src/main/frontend/src/AddRecipe.js
  Cockpybara/src/main/frontend/src/Recipe.js
Labels: :running_woman: FE, refactor

#211 레시피 디테일 - 모히또
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/cockMojito.js
Labels: :running_woman: FE, refactor

#213 코스모폴리탄 디테일 레시피 추가
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/cosmopolitan.js
Labels: :running_woman: FE, refactor

#214 올드패션드 디테일 레시피 추가
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/oldFashioned.js
Labels: :running_woman: FE, refactor

#216 마르니티 디테일
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/Martini.js
Labels: :running_woman: FE, refactor

#217 feat : 커뮤니티 칵테일 리스트 유저 이미지 추가
  Cockpybara/src/main/frontend/src/CocktailListSection.css
  Cockpybara/src/main/frontend/src/CocktailListSection.js
  Cockpybara/src/main/frontend/src/photo/user_sample.png
Labels: enhancement, :running_woman: FE

#218 Feature/#215
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/daiquiri.js
Labels: :running_woman: FE, refactor

#220 소진분량
  Cockpybara/src/main/frontend/src/AddRecipe2.css
  Cockpybara/src/main/frontend/src/AddRecipe2.js
  Cockpybara/src/main/frontend/src/App.js
  Cockpybara/src/main/frontend/src/EditProfile.css
  Cockpybara/src/main/frontend/src/EditProfile.js
  Cockpybara/src/main/frontend/src/Home.js
  Cockpybara/src/main/frontend/src/JoinComplete.js
  Cockpybara/src/main/frontend/src/MyPage.css
  Cockpybara/src/main/frontend/src/MyPage.js
  Cockpybara/src/main/frontend/src/RecipeDetail.css
  Cockpybara/src/main/frontend/src/RecipeDetail.js
  Cockpybara/src/main/frontend/src/components/Menu.css
  Cockpybara/src/main/frontend/src/photo/SLR Camera.png
  Cockpybara/src/main/frontend/src/photo/polygon.png
Labels: :running_woman: FE, refactor

#223 최종 commit
  Cockpybara/src/main/frontend/src/AddRecipe.js
  Cockpybara/src/main/frontend/src/Home.js
  Cockpybara/src/main/frontend/src/Martini.js
  Cockpybara/src/main/frontend/src/MyPage.css
  Cockpybara/src/main/frontend/src/MyPage.js
  Cockpybara/src/main/frontend/src/Recipe.js
  Cockpybara/src/main/frontend/src/RecipeDetail.css
  Cockpybara/src/main/frontend/src/RecipeDetail.js
  Cockpybara/src/main/frontend/src/cockMojito.js
  Cockpybara/src/main/frontend/src/cosmopolitan.js
  Cockpybara/src/main/frontend/src/daiquiri.js
  Cockpybara/src/main/frontend/src/oldFashioned.js
Labels: :running_woman: FE, refactor

#224 프로필 수정 수정
  Cockpybara/src/main/frontend/src/EditProfile.js
Labels: :running_woman: FE, refactor
